version: "3.4"
services:
  service-a:
    build:
      dockerfile: Dockerfile
      target: dev
      context: .
    env_file: .env
    environment:
      - SVC_DB_DATABASE=service_a
      - SVC_KAFKA_GROUP_ID=service_a
    volumes:
      - type: bind
        consistency: delegated
        source: .
        target: /app
    command: bash -c "make build-service-a migrate-service-a && ./.bin/service-a"
    ports:
      - $CONTAINER_SERVICE_A_PORT:80
    depends_on:
      - db
      - kafka

  service-b:
    build:
      dockerfile: Dockerfile
      target: dev
      context: .
    env_file: .env
    environment:
      - SVC_DB_DATABASE=service_b
      - SVC_KAFKA_GROUP_ID=service_b
    volumes:
      - type: bind
        consistency: delegated
        source: .
        target: /app
    command: bash -c "make build-service-b migrate-service-b && ./.bin/service-b"
    ports:
      - $CONTAINER_SERVICE_B_PORT:80
    depends_on:
      - db
      - kafka

  db:
    image: "postgres:14.5"
    env_file: .env
    volumes:
      - ./scripts/create_databases.sql:/docker-entrypoint-initdb.d/create_databases.sql
    ports:
      - $CONTAINER_DB_PORT:5432

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    env_file: .env
    ports:
      - $CONTAINER_KAFKA_PORT:19092
    depends_on:
      - zookeeper

  zookeeper:
    image: zookeeper:3.8.0
