// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: queries.sql

package postgres

import (
	"context"
)

const selectX = `-- name: SelectX :one
SELECT 1
`

func (q *Queries) SelectX(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, selectX)
	var column_1 interface{}
	err := row.Scan(&column_1)
	return column_1, err
}
