name: CI
on:
  workflow_dispatch:
    inputs:
      debug_ssh:
        description: "Enable SSH debug with tmate, see https://github.com/marketplace/actions/debugging-with-tmate"
        required: false
        type: boolean
        default: false
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 1" # Every Monday

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19.1" # update together with Dockerfile
      - name: Debug with tmate SSH if enabled
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_ssh }}
        uses: mxschmitt/action-tmate@v3
      - run: make test
      # test with coverage fails because go builds all packages in the same binary,
      # and there is a conflict between .proto files
      #- run: make test-cover
      #- uses: codecov/codecov-action@v3

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19.1" # update together with Dockerfile
      - uses: golangci/golangci-lint-action@v3
        with:
          version: "v1.49.0" # update together with Dockerfile

  check-tidy:
    name: go mod tidy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19.1" # update together with Dockerfile
      - run: make check-tidy

  check-vendor:
    name: vendor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19.1" # update together with Dockerfile
      - run: make check-vendor

  check-gen:
    name: code generation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19.1" # update together with Dockerfile
      - run: make check-gen
